var RestaurantsListData = [

    {   index: 1,
        price: 95,
        view: 164,
        point: 7.8,
        title: "Da Alfredo",
        time: "2h 25m",
        publishedYear: 2017,
        category: "Restaurants",
        location: "Paris Centre",
        imgUrl: "restaurant_1.jpg",
        desc: "Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.",
    },

    {   index: 2,
        price: 45,
        view: 200,
        point: 9.0,
        title: "Slow Food",
        time: "1h 25m",
        publishedYear: 2019,
        category: "Restaurants",
        location: "Paris Centre",
        imgUrl: "restaurant_2.jpg",
        desc: "Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.",
    },

    {   index: 3,
        price: 25,
        view: 143,
        point: 6.7,
        title: "Bella Napoli",
        time: "1h 15m",
        category: "Restaurants",
        publishedYear: 2000,
        location: "Paris Centre",
        imgUrl: "restaurant_3.jpg",
        desc: "Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.",
    },

    {   index: 4,
        price: 124,
        view: 120,
        point: 8.6,
        title: "Marcus",
        time: "2h 00m",
        category: "Restaurants",
        publishedYear: 2021,
        location: "Paris Centre",
        imgUrl: "restaurant_4.jpg",
        desc: "Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.",
    },

    {   index: 5,
        price: 70,
        view: 50,
        point: 7.1,
        title: "Agatha Restaurant",
        time: "2h 05m",
        category: "Restaurants",
        publishedYear: 2000,
        location: "Istanbul Beyoglu",
        imgUrl: "restaurant_5.jpg",
        desc: "Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.",
    },

    {   index: 6,
        price: 132,
        view: 100,
        point: 9.5,
        title: "Hanzade Terrace",
        time: "1h 10m",
        category: "Restaurants",
        publishedYear: 2022,
        location: "Istanbul Fatih",
        imgUrl: "restaurant_6.jpg",
        desc: "Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.",
    },

    {   index: 7,
        price: 160,
        view: 250,
        point: 9.2,
        title: "Two Cups Coffee Bar",
        time: "1h 05m",
        category: "Coffee Bars",
        publishedYear: 2021,
        location: "Izmir Konak",
        imgUrl: "coffee_bars_1.jpg",
        desc: "Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.",
    },

    {   index: 8,
        price: 120,
        view: 120,
        point: 7.5,
        title: "On A On Rock Cafe",
        category: "Coffee Bars",
        publishedYear: 2022,
        location: "Ankara Çankaya",
        imgUrl: "coffee_bars_2.jpg",
        desc: "Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.",
    },

    {   index: 9,
        price: 70,
        view: 35,
        point: 6.5,
        title: "Imagine Cafe Bar",
        category: "Coffee Bars",
        publishedYear: 2010,
        location: "Lefkosa Ledras",
        imgUrl: "coffee_bars_3.jpg",
        desc: "Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.",
    },

    {   index: 10,
        price: 150,
        view: 210,
        point: 8.0,
        title: "Rounder's Irish Pub",
        category: "Bars",
        publishedYear: 2014,
        location: "Istanbul Fatih",
        imgUrl: "bars_1.jpg",
        desc: "Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.",
    },

    {   index: 11,
        price: 300,
        view: 350,
        point: 9.1,
        title: "Mabolla Center",
        category: "Bars",
        publishedYear: 2022,
        location: "Muğla Mentese",
        imgUrl: "bars_2.jpg",
        desc: "Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.",
    },

    {   index: 12,
        price: 120,
        view: 90,
        point: 6.1,
        title: "Queen Bar",
        category: "Bars",
        publishedYear: 2022,
        location: "Yenisehir Mersin",
        imgUrl: "bars_3.jpg",
        desc: "Id placerat tacimates definitionem sea, prima quidam vim no. Duo nobis persecuti cu.",
    },
    
];